### ISSUE TITLE
Workflow messages instead of reviews?

### ISSUE THREAD

**Issue by flying-sheep** [EnriqueSoria/annotate_pr_with_ruff#2]
Is there a reason you use a review instead of the workflow message feature? https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message

**Comment by EnriqueSoria** [comment]
Because I didn't managed to make it working, but now it is. Thanks for pointing me where to start!

**Comment by flying-sheep** [comment]
neat!
